apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

android {
    compileSdkVersion 34
    namespace 'com.xpunge.example'

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }

    defaultConfig {
        applicationId 'com.xpunge.example'
        minSdkVersion 24
        targetSdkVersion 34
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        debug {
            debuggable true
        }
    }

    aaptOptions {
        noCompress 'enc'
    }
}

dependencies {
    implementation project(':library')
}
